In [1]:
import Helper as req
import json
import pandas as pd
from pandas import DataFrame
import requests

In [2]:

# GLOBAL VARIABLES

matches_file = "matches.json"
data_file = "data.pkl"
results_file = "results.json"
api_key = "RGAPI-987c33b6-6a1e-4a6f-93a4-a8edef2bd4ae"
riot_id = "Ferix8475#NA1"

gameName = riot_id.split("#")[0]
tagline = riot_id.split("#")[1]

puuid = req.fetch_account_puuid(gameName, tagline, api_key)


# UPDATE THE DATAFRAME
req.update_data(puuid=puuid, api_key=api_key)

df = pd.read_pickle(data_file)

In [3]:
df

,Champion,Role,Patch,Win,Summoner1,Summoner2,Turrets_Killed,Total_Minions_Killed,Total_Jungle_Monsters_Killed,Total_Damage_DealtToChampions,...,Flex_Rune,Offense_Rune,Primary_Tree,Primary_Keystone,Primary_Choice1,Primary_Choice2,Primary_Choice3,Secondary_Tree,Secondary_Choice1,Secondary_Choice2
0,Zed,MIDDLE,14.13,True,12,4,1,131,0,5360,...,5008,5008,8300,8369,8304,8313,8347,8200,8210,8237
0,JarvanIV,JUNGLE,14.13,False,11,4,2,15,190,30369,...,5008,5005,8000,8010,9111,9104,8014,8300,8304,8347
0,Lux,UTILITY,14.13,False,14,4,0,31,0,4263,...,5008,5008,8200,8229,8226,8210,8237,8300,8345,8347
0,Gragas,JUNGLE,14.13,False,11,4,0,28,121,13410,...,5008,5008,8200,8230,8275,8234,8232,8300,8304,8347
0,Zed,MIDDLE,14.13,True,12,4,3,233,5,40168,...,5008,5008,8300,8369,8304,8313,8347,8200,8210,8237
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,Zed,JUNGLE,13.8,True,11,4,2,25,163,29469,...,5008,5005,8300,8369,8304,8321,8347,8100,8138,8143
0,Zed,JUNGLE,13.8,True,11,4,0,4,93,4105,...,5008,5005,8300,8369,8304,8321,8347,8100,8138,8143
0,Darius,TOP,13.7,False,6,4,1,129,0,12458,...,5008,5005,8000,8010,9111,9105,8299,8400,8473,8242
0,Darius,TOP,13.7,False,6,4,3,243,0,21406,...,5008,5005,8000,8010,9111,9105,8299,8400,8242,8473
0,Darius,TOP,13.7,True,6,4,4,244,0,15835,...,5008,5005,8000,8010,9111,9104,8299,8400,8444,8242

In [4]:
effectiveness_df = df.groupby(['Champion', 'Role', 'Win']).agg({
        'Total_Minions_Killed': 'mean',
        'Total_Jungle_Monsters_Killed': 'mean',
        'Total_Damage_DealtToChampions': 'mean',
        'KDA': 'mean',
        'Kill_Participation': 'mean',
        'Damage_Share': 'mean',
        'Turret_Plates_Taken': 'mean',
        'Gold_Per_Minute': 'mean',
        'Damage_Per_Minute': 'mean',
        'Vision_Score_Per_Minute': 'mean',
        'Lane_Minions_Before_10_Minutes': 'mean',
        'Jungle_CS_Before_10_Minutes': 'mean',
        'Sol_Kills':'mean'

})
effectiveness_df

                        Total_Minions_Killed  Total_Jungle_Monsters_Killed  \
Champion Role    Win
Aatrox           False             39.000000                      6.500000
                 True              97.000000                     18.500000
         JUNGLE  False             17.400000                    107.800000
                 True              32.000000                    143.000000
         MIDDLE  False            116.000000                      0.000000
...                                      ...                           ...
Zed      MIDDLE  True             193.583333                      6.694444
         TOP     False            211.000000                      5.000000
                 True             239.000000                     38.333333
         UTILITY False             53.000000                      0.000000
                 True             115.000000                      8.000000

                        Total_Damage_DealtToChampions       KDA  \
Champion Role    Win
Aatrox           False                   23789.500000       NaN
                 True                    33594.000000       NaN
         JUNGLE  False                    6251.800000  1.233333
                 True                    17619.500000  3.166667
         MIDDLE  False                   12644.000000  0.902778
...                                               ...       ...
Zed      MIDDLE  True                    27092.222222  4.376786
         TOP     False                   21874.000000  0.400000
                 True                    65826.333333  5.933333
         UTILITY False                   20131.000000  1.428571
                 True                    39073.000000  2.571429

                        Kill_Participation  Damage_Share Turret_Plates_Taken  \
Champion Role    Win
Aatrox           False                 NaN           NaN                 NaN
                 True                  NaN           NaN                 NaN
         JUNGLE  False            0.286486      0.106599                 0.4
                 True             0.357558      0.162618                 0.0
         MIDDLE  False            0.291379      0.214181                 0.5
...                                    ...           ...                 ...
Zed      MIDDLE  True             0.418480      0.247488            2.611111
         TOP     False            0.181818      0.183768                 1.0
                 True             0.555820      0.341064            3.333333
         UTILITY False            0.454545      0.248205                 1.0
                 True             0.375000      0.201061                 0.0

                        Gold_Per_Minute  Damage_Per_Minute  \
Champion Role    Win
Aatrox           False              NaN                NaN
                 True               NaN                NaN
         JUNGLE  False       336.544357         238.364878
                 True        391.677828         474.186637
         MIDDLE  False       385.095136         561.395316
...                                 ...                ...
Zed      MIDDLE  True        473.071785         843.890990
         TOP     False       320.356173         584.754435
                 True        569.965314        1631.315158
         UTILITY False       331.607087         757.125193
                 True        331.672700         900.468560

                        Vision_Score_Per_Minute  \
Champion Role    Win
Aatrox           False                      NaN
                 True                       NaN
         JUNGLE  False                 0.723166
                 True                  0.823045
         MIDDLE  False                 0.643855
...                                         ...
Zed      MIDDLE  True                  0.748804
         TOP     False                 0.835389
                 True                  0.928978
         UTILITY False                 2.218990
                 True                  2.252129

                       Lane_Minions_Before_10_Minutes  \
Champion Role    Win
Aatrox           False                            NaN
                 True                             NaN
         JUNGLE  False                            0.0
                 True                             2.0
         MIDDLE  False                           51.5
...                                               ...
Zed      MIDDLE  True                           66.25
         TOP     False                           59.0
                 True                            79.0
         UTILITY False                           14.0
                 True                            11.0

                        Jungle_CS_Before_10_Minutes Sol_Kills
Champion Role    Win
Aatrox           False                          NaN       NaN
                 True                           NaN       NaN
         JUNGLE  False                    54.110000       0.0
                 True                     56.500000       1.5
         MIDDLE  False                     0.000000       1.0
...                                             ...       ...
Zed      MIDDLE  True                      0.088889  3.638889
         TOP     False                     0.000000       2.0
                 True                      0.000000       6.0
         UTILITY False                     0.000000       2.0
                 True                      0.000000       2.0

[172 rows x 13 columns]

In [5]:
winrate_by_role = df.groupby(['Champion', 'Role']).agg(
    Winrate=('Win', 'mean'),
    Games_Played=('Win', 'count')
)
winrate_by_role

                   Winrate  Games_Played
Champion Role
Aatrox            0.500000             4
         JUNGLE   0.285714             7
         MIDDLE   0.500000             4
         TOP      0.440000            25
         UTILITY  0.307692            13
...                    ...           ...
Zed               0.769231            13
         JUNGLE   0.551724            58
         MIDDLE   0.545455            66
         TOP      0.750000             4
         UTILITY  0.500000             2

[118 rows x 2 columns]

In [20]:
runes = req.json_extract_runes()
treepage = {
    8000: "Precision",
    8100: "Domination",
    8200: "Sorcery",
    8300: "Inspiration",
    8400: "Resolve"
}


df['Primary_Tree'] = df['Primary_Tree'].replace(treepage)
df['Secondary_Tree'] = df['Secondary_Tree'].replace(treepage)
df['Primary_Keystone'] = df['Primary_Keystone'].replace(runes)
runes

{8369: 'First Strike',
 8446: 'Demolish',
 8126: 'Cheap Shot',
 8415: 'The Arcane Colossus',
 8410: 'Approach Velocity',
 8232: 'Waterwalking',
 8299: 'Last Stand',
 8112: 'Electrocute',
 8234: 'Celerity',
 8453: 'Revitalize',
 8360: 'Unsealed Spellbook',
 8004: 'The Brazen Perfect',
 8128: 'Dark Harvest',
 8220: 'The Calamity',
 8016: 'The Merciless Elite',
 8473: 'Bone Plating',
 8339: 'Celestial Body',
 8214: 'Summon Aery',
 8237: 'Scorch',
 8139: 'Taste of Blood',
 9101: 'Absorb Life',
 8008: 'Lethal Tempo',
 8010: 'Conqueror',
 9105: 'Legend: Haste',
 8106: 'Ultimate Hunter',
 8017: 'Cut Down',
 8224: 'Nullifying Orb',
 8210: 'Transcendence',
 8005: 'Press the Attack',
 8435: 'Mirror Shell',
 8115: 'The Aether Blade',
 8359: 'Kleptomancy',
 8352: 'Time Warp Tonic',
 5003: 'Magic Resist',
 8135: 'Treasure Hunter',
 8120: 'Ghost Poro',
 8134: 'Ingenious Hunter',
 8351: 'Glacial Augment',
 8242: 'Unflinching',
 8401: 'Shield Bash',
 9111: 'Triumph',
 8105: 'Relentless Hunter',
 8454: 'The Leviathan',
 8275: 'Nimbus Cloak',
 8207: 'The Cryptic',
 5012: 'Resist Scaling',
 8439: 'Aftershock',
 8109: 'The Wicked Maestro ',
 5002: 'Armor',
 5011: 'Health',
 5013: 'Tenacity and Slow Resist',
 8414: 'The Behemoth',
 5008: 'Adaptive Force',
 8320: 'The Timeless',
 8319: 'The Stargazer',
 5001: 'Health Scaling',
 8430: 'Iron Skin',
 8014: 'Coup de Grace',
 5007: 'Ability Haste',
 8021: 'Fleet Footwork',
 8226: 'Manaflow Band',
 8451: 'Overgrowth',
 8313: 'Triple Tonic',
 9103: 'Legend: Bloodline',
 8114: 'The Immortal Butcher',
 8230: 'Phase Rush',
 8318: 'The Ruthless Visionary',
 8463: 'Font of Life',
 7000: 'Template',
 8304: 'Magical Footwear',
 8236: 'Gathering Storm',
 8009: 'Presence of Mind',
 8006: 'The Eternal Champion',
 9104: 'Legend: Alacrity',
 8416: 'The Enlightened Titan',
 5005: 'Attack Speed',
 8306: 'Hextech Flashtraption',
 8465: 'Guardian',
 8138: 'Eyeball Collection',
 5010: 'Move Speed',
 8127: 'The Twisted Surgeon',
 8143: 'Sudden Impact',
 8345: 'Biscuit Delivery',
 8444: 'Second Wind',
 8205: 'The Incontestable Spellslinger',
 8437: 'Grasp of the Undying',
 9923: 'Hail of Blades',
 8429: 'Conditioning',
 8124: 'Predator',
 8233: 'Absolute Focus',
 8007: 'The Savant',
 8136: 'Zombie Ward',
 8208: 'The Ancient One',
 8347: 'Cosmic Insight',
 8472: 'Chrysalis',
 8316: 'Jack Of All Trades',
 8229: 'Arcane Comet',
 8344: 'The Elegant Duelist ',
 8321: 'Cash Back'}

In [21]:
moregrouped = df.groupby(['Champion', 'Role', 'Primary_Tree', 'Secondary_Tree']).agg(
    Winrate=('Win', 'mean'),
    Games_Played=('Win', 'count')
)
moregrouped

                                               Winrate  Games_Played
Champion Role    Primary_Tree Secondary_Tree
Aatrox           Precision    Domination      0.500000             4
         JUNGLE  Precision    Domination      0.285714             7
         MIDDLE  Precision    Resolve         0.500000             4
         TOP     Precision    Domination      0.000000             1
                              Resolve         0.458333            24
...                                                ...           ...
Zed      MIDDLE  Precision    Sorcery         0.500000             2
         TOP     Domination   Inspiration     0.000000             1
                              Sorcery         1.000000             2
                 Precision    Domination      1.000000             1
         UTILITY Domination   Sorcery         0.500000             2

[181 rows x 2 columns]

In [22]:
keystone_runes_df = df.groupby(['Champion', 'Role', 'Primary_Keystone', 'Secondary_Tree']).agg(
    Winrate=('Win', 'mean'),
    Games_Played=('Win', 'count')
)
keystone_runes_df

                                                   Winrate  Games_Played
Champion Role    Primary_Keystone Secondary_Tree
Aatrox           Conqueror        Domination      0.500000             4
         JUNGLE  Conqueror        Domination      0.285714             7
         MIDDLE  Conqueror        Resolve         0.500000             4
         TOP     Conqueror        Domination      0.000000             1
                                  Resolve         0.458333            24
...                                                    ...           ...
Zed      MIDDLE  First Strike     Sorcery         0.600000            15
         TOP     Conqueror        Domination      1.000000             1
                 Electrocute      Inspiration     0.000000             1
                                  Sorcery         1.000000             2
         UTILITY Electrocute      Sorcery         0.500000             2

[184 rows x 2 columns]

In [9]:
print(req.json_extract_runes())
treepage = {
    8000: "Precision",
    8100: "Domination",
    8200: "Sorcery",
    8300: "Inspiration",
    8400: "Resolve"
}

{8369: 'First Strike', 8446: 'Demolish', 8126: 'Cheap Shot', 8415: 'The Arcane Colossus', 8410: 'Approach Velocity', 8232: 'Waterwalking', 8299: 'Last Stand', 8112: 'Electrocute', 8234: 'Celerity', 8453: 'Revitalize', 8360: 'Unsealed Spellbook', 8004: 'The Brazen Perfect', 8128: 'Dark Harvest', 8220: 'The Calamity', 8016: 'The Merciless Elite', 8473: 'Bone Plating', 8339: 'Celestial Body', 8214: 'Summon Aery', 8237: 'Scorch', 8139: 'Taste of Blood', 9101: 'Absorb Life', 8008: 'Lethal Tempo', 8010: 'Conqueror', 9105: 'Legend: Haste', 8106: 'Ultimate Hunter', 8017: 'Cut Down', 8224: 'Nullifying Orb', 8210: 'Transcendence', 8005: 'Press the Attack', 8435: 'Mirror Shell', 8115: 'The Aether Blade', 8359: 'Kleptomancy', 8352: 'Time Warp Tonic', 5003: 'Magic Resist', 8135: 'Treasure Hunter', 8120: 'Ghost Poro', 8134: 'Ingenious Hunter', 8351: 'Glacial Augment', 8242: 'Unflinching', 8401: 'Shield Bash', 9111: 'Triumph', 8105: 'Relentless Hunter', 8454: 'The Leviathan', 8275: 'Nimbus Cloak', 8207: 'The Cryptic', 5012: 'Resist Scaling', 8439: 'Aftershock', 8109: 'The Wicked Maestro ', 5002: 'Armor', 5011: 'Health', 5013: 'Tenacity and Slow Resist', 8414: 'The Behemoth', 5008: 'Adaptive Force', 8320: 'The Timeless', 8319: 'The Stargazer', 5001: 'Health Scaling', 8430: 'Iron Skin', 8014: 'Coup de Grace', 5007: 'Ability Haste', 8021: 'Fleet Footwork', 8226: 'Manaflow Band', 8451: 'Overgrowth', 8313: 'Triple Tonic', 9103: 'Legend: Bloodline', 8114: 'The Immortal Butcher', 8230: 'Phase Rush', 8318: 'The Ruthless Visionary', 8463: 'Font of Life', 7000: 'Template', 8304: 'Magical Footwear', 8236: 'Gathering Storm', 8009: 'Presence of Mind', 8006: 'The Eternal Champion', 9104: 'Legend: Alacrity', 8416: 'The Enlightened Titan', 5005: 'Attack Speed', 8306: 'Hextech Flashtraption', 8465: 'Guardian', 8138: 'Eyeball Collection', 5010: 'Move Speed', 8127: 'The Twisted Surgeon', 8143: 'Sudden Impact', 8345: 'Biscuit Delivery', 8444: 'Second Wind', 8205: 'The Incontestable Spellslinger', 8437: 'Grasp of the Undying', 9923: 'Hail of Blades', 8429: 'Conditioning', 8124: 'Predator', 8233: 'Absolute Focus', 8007: 'The Savant', 8136: 'Zombie Ward', 8208: 'The Ancient One', 8347: 'Cosmic Insight', 8472: 'Chrysalis', 8316: 'Jack Of All Trades', 8229: 'Arcane Comet', 8344: 'The Elegant Duelist ', 8321: 'Cash Back'}